### ISSUE TITLE
Breaks with webpack 2!

### ISSUE THREAD

**Issue by ShyamRaj** [aaronj1335/webpack-postcss-tools#13] opened 2017-03-24 20:02 UTC
The new version of webpack is making the package to not work as it was before, Is someone maintaining this project still?

**Comment by aaronj1335** [comment] 2017-03-28 15:42
Steps to reproduce the issue? Stack trace? Sample project where you can see the issue?

Closing this since there's no actionable info. Feel free to re-open if you can provide.

**Closed as completed by aaronj1335** 2017-03-28 15:42 UTC
